### ISSUE TITLE
Some error in syntax

### ISSUE THREAD

**Issue by ghost** [krambertech/fp-webinar#1]
You lost one point in `sum(...args)`

```
function sum(..args) {
    return args.reduce((result, item) => result + item, 0);
}
```

**Comment by krambertech** [comment]
Спасибо. Извиняюсь, я регулярно пропускаю нотификации в гитхабе :) 

Код писала тут не запуская, так что подобные вещи вполне закономерны.

**Comment by krambertech** [comment]
PR смерджила
